"""first migration

Revision ID: b6b6b942ab45
Revises: 
Create Date: 2022-01-20 14:13:53.426817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6b6b942ab45'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'admin_login', ['id'])
    op.create_unique_constraint(None, 'advance_care_directive', ['id'])
    op.create_unique_constraint(None, 'alcohol_consumption', ['id'])
    op.create_unique_constraint(None, 'allergies_and_intolerances', ['id'])
    op.create_unique_constraint(None, 'allergy', ['id'])
    op.create_unique_constraint(None, 'care_plan', ['care_plan_id'])
    op.create_unique_constraint(None, 'diagnostic_test_result', ['id'])
    op.create_unique_constraint(None, 'doctor_details', ['id'])
    op.create_unique_constraint(None, 'functional_status', ['id'])
    op.create_unique_constraint(None, 'history_of_procedures', ['id'])
    op.create_unique_constraint(None, 'immunization', ['id'])
    op.create_unique_constraint(None, 'immunizations', ['id'])
    op.create_unique_constraint(None, 'limitation_of_treatment', ['id'])
    op.create_unique_constraint(None, 'medical_devices', ['id'])
    op.create_unique_constraint(None, 'medication_order', ['medId'])
    op.create_unique_constraint(None, 'medication_statement', ['order_id'])
    op.create_unique_constraint(None, 'medication_summary', ['medication_summary_id'])
    op.create_unique_constraint(None, 'past_history_of_illnesses', ['id'])
    op.create_unique_constraint(None, 'patient_details', ['id'])
    op.create_unique_constraint(None, 'pregnancy', ['id'])
    op.create_unique_constraint(None, 'prescription', ['id'])
    op.create_unique_constraint(None, 'problem', ['id'])
    op.create_unique_constraint(None, 'problem_list', ['id'])
    op.create_unique_constraint(None, 'procedure', ['id'])
    op.create_unique_constraint(None, 'service_request', ['id'])
    op.create_unique_constraint(None, 'tobacco_smoking', ['id'])
    op.create_unique_constraint(None, 'vital_signs', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vital_signs', type_='unique')
    op.drop_constraint(None, 'tobacco_smoking', type_='unique')
    op.drop_constraint(None, 'service_request', type_='unique')
    op.drop_constraint(None, 'procedure', type_='unique')
    op.drop_constraint(None, 'problem_list', type_='unique')
    op.drop_constraint(None, 'problem', type_='unique')
    op.drop_constraint(None, 'prescription', type_='unique')
    op.drop_constraint(None, 'pregnancy', type_='unique')
    op.drop_constraint(None, 'patient_details', type_='unique')
    op.drop_constraint(None, 'past_history_of_illnesses', type_='unique')
    op.drop_constraint(None, 'medication_summary', type_='unique')
    op.drop_constraint(None, 'medication_statement', type_='unique')
    op.drop_constraint(None, 'medication_order', type_='unique')
    op.drop_constraint(None, 'medical_devices', type_='unique')
    op.drop_constraint(None, 'limitation_of_treatment', type_='unique')
    op.drop_constraint(None, 'immunizations', type_='unique')
    op.drop_constraint(None, 'immunization', type_='unique')
    op.drop_constraint(None, 'history_of_procedures', type_='unique')
    op.drop_constraint(None, 'functional_status', type_='unique')
    op.drop_constraint(None, 'doctor_details', type_='unique')
    op.drop_constraint(None, 'diagnostic_test_result', type_='unique')
    op.drop_constraint(None, 'care_plan', type_='unique')
    op.drop_constraint(None, 'allergy', type_='unique')
    op.drop_constraint(None, 'allergies_and_intolerances', type_='unique')
    op.drop_constraint(None, 'alcohol_consumption', type_='unique')
    op.drop_constraint(None, 'advance_care_directive', type_='unique')
    op.drop_constraint(None, 'admin_login', type_='unique')
    # ### end Alembic commands ###
