"""added address of patient

Revision ID: f3cd0c5289f3
Revises: b6b6b942ab45
Create Date: 2022-01-20 14:15:08.413935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3cd0c5289f3'
down_revision = 'b6b6b942ab45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient_details', sa.Column('address', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patient_details', 'address')
    # ### end Alembic commands ###
